Repository Tencent/tdesign-miniprogram, pull requests merged in 2022-07, with the labels that each got.

#619 fix(drawer): placement remove top and bottom
  src/drawer/README.md
  src/drawer/drawer.wxml
  src/drawer/props.ts
  src/drawer/type.ts
Labels: BreakingChanges

#603 docs(button): update docs
  src/button/README.md
  src/button/button.ts
Labels: BreakingChanges

#617 feat(Skeleton): theme support five base type
  example/app.json
  src/skeleton/README.md
  src/skeleton/_example/animation/index.js
  src/skeleton/_example/animation/index.json
  src/skeleton/_example/animation/index.wxml
  src/skeleton/_example/animation/index.wxss
  src/skeleton/_example/cell-group/index.js
  src/skeleton/_example/cell-group/index.json
  src/skeleton/_example/cell-group/index.wxml
  src/skeleton/_example/cell-group/index.wxss
  src/skeleton/_example/grid/index.js
  src/skeleton/_example/grid/index.json
  src/skeleton/_example/grid/index.wxml
  src/skeleton/_example/grid/index.wxss
  src/skeleton/_example/image-group/index.js
  src/skeleton/_example/image-group/index.json
  src/skeleton/_example/image-group/index.wxml
  src/skeleton/_example/image-group/index.wxss
  src/skeleton/_example/skeleton.json
  src/skeleton/_example/skeleton.less
  src/skeleton/_example/skeleton.ts
  src/skeleton/_example/skeleton.wxml
  src/skeleton/_example/theme/index.js
  src/skeleton/_example/theme/index.json
  src/skeleton/_example/theme/index.wxml
  src/skeleton/_example/theme/index.wxss
  src/skeleton/props.ts
  src/skeleton/skeleton.less
  src/skeleton/skeleton.ts
  src/skeleton/skeleton.wxml
  src/skeleton/skeleton.wxs
  src/skeleton/type.ts
Labels: BreakingChanges

#650 fix(tabbar): remove color property add new css variable
  src/tab-bar/README.md
  src/tab-bar/_example/badge/index.wxml
  src/tab-bar/_example/custom/index.js
  src/tab-bar/_example/custom/index.json
  src/tab-bar/_example/custom/index.wxml
  src/tab-bar/_example/custom/index.wxss
  src/tab-bar/_example/tab-bar.json
  src/tab-bar/_example/tab-bar.wxml
  src/tab-bar/props.ts
  src/tab-bar/tab-bar-item.less
  src/tab-bar/tab-bar-item.ts
  src/tab-bar/tab-bar-item.wxml
  src/tab-bar/tab-bar.ts
  src/tab-bar/tab-bar.wxml
  src/tab-bar/type.ts
Labels: breaking changes

#653 docs(rate): update code sample
  src/rate/README.md
  src/rate/_example/allow-half/index.js
  src/rate/_example/allow-half/index.json
  src/rate/_example/allow-half/index.wxml
  src/rate/_example/allow-half/index.wxss
  src/rate/_example/api.md
  src/rate/_example/base/index.js
  src/rate/_example/base/index.json
  src/rate/_example/base/index.wxml
  src/rate/_example/base/index.wxss
  src/rate/_example/color/index.js
  src/rate/_example/color/index.json
  src/rate/_example/color/index.wxml
  src/rate/_example/color/index.wxss
  src/rate/_example/count/index.js
  src/rate/_example/count/index.json
  src/rate/_example/count/index.wxml
  src/rate/_example/count/index.wxss
  src/rate/_example/disabled/index.js
  src/rate/_example/disabled/index.json
  src/rate/_example/disabled/index.wxml
  src/rate/_example/disabled/index.wxss
  src/rate/_example/rate.json
  src/rate/_example/rate.less
  src/rate/_example/rate.ts
  src/rate/_example/rate.wxml
  src/rate/_example/show-text/index.js
  src/rate/_example/show-text/index.json
  src/rate/_example/show-text/index.wxml
  src/rate/_example/show-text/index.wxss
  src/rate/_example/size/index.js
  src/rate/_example/size/index.json
  src/rate/_example/size/index.wxml
  src/rate/_example/size/index.wxss
  src/rate/_example/un-filled/index.js
  src/rate/_example/un-filled/index.json
  src/rate/_example/un-filled/index.wxml
  src/rate/_example/un-filled/index.wxss
  src/rate/props.ts
  src/rate/rate.less
  src/rate/rate.ts
  src/rate/rate.wxml
  src/rate/rate.wxs
  src/rate/type.ts
Labels: breaking changes

#663 fix(tabbar): add fallback to CSS variables
  src/tab-bar/tab-bar-item.less
  src/tab-bar/tab-bar.less
Labels: breaking changes

#665 docs(Avatar): update code sample
  src/avatar/README.md
  src/avatar/_example/action/index.js
  src/avatar/_example/action/index.json
  src/avatar/_example/action/index.wxml
  src/avatar/_example/action/index.wxss
  src/avatar/_example/avatar.json
  src/avatar/_example/avatar.less
  src/avatar/_example/avatar.ts
  src/avatar/_example/avatar.wxml
  src/avatar/_example/exhibition/index.js
  src/avatar/_example/exhibition/index.json
  src/avatar/_example/exhibition/index.wxml
  src/avatar/_example/exhibition/index.wxss
  src/avatar/_example/shape/index.js
  src/avatar/_example/shape/index.json
  src/avatar/_example/shape/index.wxml
  src/avatar/_example/shape/index.wxss
  src/avatar/_example/size/index.js
  src/avatar/_example/size/index.json
  src/avatar/_example/size/index.wxml
  src/avatar/_example/size/index.wxss
  src/avatar/avatar-group.less
  src/avatar/avatar-group.ts
  src/avatar/avatar-group.wxml
  src/avatar/avatar-group.wxs
  src/avatar/avatar.less
  src/avatar/avatar.ts
  src/avatar/avatar.wxml
  src/avatar/avatar.wxs
  src/avatar/common.less
Labels: breaking changes

#666 fix(upload): fix image style
  src/grid/grid-item.less
  src/upload/upload.wxml
Labels: bug
